"""empty message

Revision ID: 00566ddad000
Revises: 
Create Date: 2021-08-27 11:37:37.649274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00566ddad000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=180), nullable=False),
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=180), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cart', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart'], ['cart.cart_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('cart')
    # ### end Alembic commands ###
