export SECRET="password123"
export AUTH0_DOMAIN='m-mark-frazier.us.auth0.com'
export API_AUDIENCE='grainy'
export ALGORITHMS=['RS256']
export FLASK_APP=flaskr
export FLASK_ENV=development
export TEST_DATABASE_URI="postgres://localhost:5432/grainydays"
export DATABASE_URI="postgres://localhost:5432/grainydays"
export NEW_VAR="Testing export"